add_product_custom_image:
  path: /custom-product-images/add/{idProduct}
  methods: [POST]
  defaults:
    _controller: 'CustomProductImages\Controller\Admin\ProductCustomImageController::addAction'
delete_product_custom_image_url:
  path: /custom-product-images/delete/{idCustomImage}
  methods: [POST]
  defaults:
    _controller: 'CustomProductImages\Controller\Admin\ProductCustomImageController::deleteAction'